#!/bin/sh

TARGET=en-us-adapted
echo "creating ./$TARGET model"

set -x

rm -fR $TARGET
cp -a en-us en-us-adapted

# produce *.mfc
cd simon
sphinx_fe -argfile ../en-us/feat.params \
	-samprate 16000 -c simon.fileids \
	-di . -do . -ei wav -eo mfc -mswav yes

# produce mdef.txt
pocketsphinx_mdef_convert -text ../en-us/mdef ../en-us/mdef.txt

# create model in $TARGET
/usr/lib/sphinxtrain/map_adapt \
    -moddeffn ../en-us/mdef.txt \
    -ts2cbfn .cont. \
    -meanfn ../en-us/means \
    -varfn ../en-us/variances \
    -mixwfn ../en-us/mixture_weights \
    -tmatfn ../en-us/transition_matrices \
    -accumdir . \
    -mapmeanfn ../$TARGET/means \
    -mapvarfn ../$TARGET/variances \
    -mapmixwfn ../$TARGET/mixture_weights \
    -maptmatfn ../$TARGET/transition_matrices

# save space
cd ../$TARGET
/usr/lib/sphinxtrain/mk_s2sendump \
    -pocketsphinx yes \
    -moddeffn mdef.txt \
    -mixwfn mixture_weights \
    -sendumpfn sendump

# clean
rm mixture_weights mdef.txt

echo "Model ./$TARGET is ready"
